### ISSUE TITLE
Possible memory leak on windows 11

### ISSUE THREAD

**Issue by tubzby** [nulldotblack/wintun#16]
Thanks for your crate!

Recently I have been working on a project utilize`https://github.com/meh/rust-tun`. 

Shortly after I finished the code  I quickly noticed some possible memory leaks, the original issue: https://github.com/meh/rust-tun/issues/83.

I haven't done memory profile for rust program on Windows before, can you help to identify the issue?

**Comment by TroyNeubauer** [comment]
Fixed upstream by: https://github.com/meh/rust-tun/issues/83#issuecomment-2082279796
