### ISSUE TITLE
socket didn't receive the response packet while wireshark caught

### ISSUE THREAD

**Issue by lazytiger** [nulldotblack/wintun#5]
I write a demo application to send DNS queries through a socks5 proxy, and it all works well except dnslookup doesn't get the response packet. I have tried to capture the response packet with wireshark，and it's there. I think this problem may have nothing to do with wintun wrapper，but I do want some advises from you guys, thanks.

**Comment by nifanfa** [comment]
hello lazytiger how did you managed to solve this problem
